### DISCUSSION TITLE
dark variant with HSL colour converting to variant group

### DISCUSSION THREAD

**Discussion by hrishikesh-k** [windicss/windicss#688] [Q&A]
Hello all.

I'm using WindiCSS (v3.4.3) in a Hugo project using the CLI. So far, the development has been a breeze, but at this point it appears that I've stumbled onto an issue.

Here's my `windi.config.js` to start with:

```js
const {defineConfig} = require('windicss/helpers')
// noinspection JSUnusedGlobalSymbols
module.exports = defineConfig({
  attributify: {
    prefix: 'w:'
  },
  darkMode: 'class',
  extract: {
    include: ['./layouts/**/*.html']
  }
})
```

...and here's where I appear to be running into issues:

```html
<body
  w:bg = "[hsl(175,48%,98%)] dark:[hsl(195,76%,3%)]">
  <!-- other stuff -->
</body>
```

I'm assuming this setup should work correctly for setting the correct background colours based on the class name in HTML. However, it does not. Upon close inspection, I can see that the generated class name is like:

```css
.dark [w\:bg~="dark:[hsl(195,.dark 76%,.dark 3%)]"] {
  --tw-bg-opacity: 1;
  background-color: rgba(2,11,13,var(--tw-bg-opacity))
}
```

...whereas, the correct class should have been:

```css
.dark [w\:bg~="dark:[hsl(195,76%,3%)]"] {
  --tw-bg-opacity: 1;
  background-color: rgba(2,11,13,var(--tw-bg-opacity))
}
```

The same code works if I change my Windi Config's dark mode to `media`.

Did I run into a bug, or is this not how it's supposed to work?
