### DISCUSSION TITLE
Variant Auto Infer

### DISCUSSION THREAD

**Discussion by louiss0** [windicss/windicss#809] [General]
Tailwindcss added a new feature that will change everything forever. arbitrary variants. You can type the name of any pseudo-class or pseudo-element in brackets then it will infer it as a variant

```html
<progress id="file" value="32" max="100" class="[::webkit-progress-value]:w-1/2" ></progress>

``` 

```CSS

.webkit-progress-value:w-1/2::-webkit-progress-value {
width: 50%;
} 

```

```html 

<div>
<div></div>
<div class="[nth-child(2)]:h-2"></div>
<div></div>
<div></div>
</div>

```

```css

.nth-child(2):h-2:nth-child(2) {

height: 0.5rem;

}

```
