### DISCUSSION TITLE
variants not working with combined selectors if not written in nested syntax

### DISCUSSION THREAD

**Discussion by posporus** [windicss/windicss#834] [Q&A]
I have the following code added using `addComponents()` as a plugin:
```js
addComponents({
    //...
    '.not-nested': {
        backgroundColor: 'red',
    },
    '.not-nested > *': {
        color: 'blue',
    },

    '.nested': {
        backgroundColor: 'green',
        '> *': {
            color: 'yellow',
        },
    },
})
```
Using `md:nested` and `md:not-nested` in my HTML produces the following CSS:
```css
/**
...
*/
.not-nested {
	background-color: red;
}
.not-nested > * {
	color: blue;
}
.nested {
	background-color: green;
}
.nested > * {
	color: yellow;
}
@media (min-width: 768px) {
	.md\:not-nested {
		background-color: red;
	}
	.md\:nested {
		background-color: green;
	}
	.md\:nested > * {
		color: yellow;
	}
}
```
As you can see, it only produces media queries for `md\:nested > *` but not for `md\:not-nested > *` as I would expect. Why is that? Shouldn't both writings have a similar output and produce also `.md\:not-nested > *`?
This also happens with any other variant that I've tried.

[->This scenario on stackblitz](https://stackblitz.com/edit/node-bpuzbx?file=windi.config.ts)

*vite 3.0.9*
*windicss 3.5.6*
