### ISSUE TITLE
Disable cross browser support

### ISSUE THREAD

**Issue by voorjaar** [windicss/windicss#132]
```css
.windi-18feqd2{
    display:-webkit-box;
    display:-ms-flexbox;
    display:-webkit-flex;
    display:flex;
}
```

to 

```css
.windi-18fe1d2 {
    display: flex;
}
```
