### ISSUE TITLE
Can you convert hex to 'rgb'a  to take advantage of opacity

### ISSUE THREAD

**Issue by germsb** [windicss/windicss#146]
### Variables

```js
bg-$${variableName}

.bg-$test-variable {
  --tw-bg-opacity: 1;
  background-color: rgba(var(--test-variable), var(--tw-bg-opacity));
}
```

### if I do :

```css
:root {
    --primary: theme('colors.indigo.500');
}
```
```html
<div class="bg-$primary"> test </div>
```

### I get: 

```css
:root {
    --primary: #6366f1;
}
.bg-\$primary {
    background-color: var(--primary);
}
```

**Comment by germsb** [comment]
maybe something like:

```css 
:root {
    --primary: theme('colors.indigo.500').toRGB;  /* --> 99, 102, 241 */
}
```
finally it's easy to add ocpacity
```css
.bg-$tprimary {
  --tw-bg-opacity: 1;
  background-color: rgba(var(--primary), var(--tw-bg-opacity));
}
```

**Comment by voorjaar** [comment]
I did this before. but this guy said some disadvantage of this behavior. so I removed it. I will consider it again now.

https://github.com/windicss/windicss/issues/72#issuecomment-781614218

**Comment by germsb** [comment]
The goal is to get something consistent.
If I use color related utility class based on variable, I expect it to behave like other color utilities classes. eg: opacity

Currently in tailwind, to obtain this result, it's quite tedious: 
In this exemple, I declare new color based on variable and describes a function that allows you to change the value of the variable on the fly

I declare the variables like this
```css
:root {
    --color-primary: 59, 130, 246;  /*  colors.blue.500. In tailwind.config,
    it's not possible to convert hex to rgb, so we have to do it manually  :( */

    /* user variables choice */
    --color-prim-1: theme('colors.blue.500');
    --color-prim-2: theme('colors.purple.500');
    --color-prim-3: theme('colors.rose.500');
    --color-prim-4: theme('colors.pink.500');
    --color-prim-5: theme('colors.yellow.500');
    --color-prim-6: theme('colors.green.500');
}
```
add opacity in tailwind.config.js
```js
const varToRgba = colorValue => ({opacityVariable, opacityValue}) => {
    if (opacityValue !== undefined) {
        return `rgba(var(${colorValue}), ${opacityValue})`;
    }
    if (opacityVariable !== undefined) {
        return `rgba(var(${colorValue}), var(${opacityVariable}, 1))`;
    }
    return `rgb(var(${colorValue}))`;
};

// ...
theme: {
        extend: {
            colors: {
                primary: varToRgba('--color-primary'),
            },
// ...
```
and then, somewhere in my app, I give the user the option to change the primary color:

```ts
const hex2rgb = (hex: string) => {
    const c = parseInt(hex.replace('#', ''), 16) ;
    return `${c >> 16}, ${(c & 0xff00) >> 8}, ${c & 0xff}`;
};
const changePrimaryColor = (primaryNumber: number) => {
            const hexColor = getComputedStyle(document.documentElement)
                .getPropertyValue(`--color-prim-${primaryNumber}`);
            const rgbColor = hex2rgb(hexColor);
            document.documentElement.style
                .setProperty('--color-primary', rgbColor);
        },
```
Fioutchh, not the easiest, but it works !

You may need to keep this approach for colors added from the tailwind.config file in order not to destabilize tailwind users.

On the other hand, since windicss offers a new way of handling variables, .eg: `bg-$my-variable`, it would be interesting to provide the possibility to get the theme colors in rgb `--my-variable: theme('colors.indigo.500').toRGB;` which would allow the generation of the linked classes .eg:
```css
.bg-$my-variable {
  --tw-bg-opacity: 1;
  background-color: rgba(var(--primary), var(--tw-bg-opacity));
}
```

Finally my tailwind logic would look like this with windicss:

```css
:root {
    --color-primary:theme('colors.blue.500').toRGB;
    /* user variables choice */
    --color-prim-1: theme('colors.blue.500').toRGB;
    --color-prim-2: theme('colors.purple.500').toRGB;
    --color-prim-3: theme('colors.rose.500').toRGB;
    --color-prim-4: theme('colors.pink.500').toRGB;
    --color-prim-5: theme('colors.yellow.500').toRGB;
    --color-prim-6: theme('colors.green.500').toRGB;
}
```
```ts
const changePrimaryColor = (primaryNumber: number) => {
            const rgbColor = getComputedStyle(document.documentElement)
                .getPropertyValue(`--color-prim-${primaryNumber}`);
            document.documentElement.style
                .setProperty('--color-primary', rgbColor);
},
```
#### More easier, isn't it ? :)
