### ISSUE TITLE
Issue with css output with referenced images in stylesheet

### ISSUE THREAD

**Issue by fabd** [windicss/windicss#153]
Just fyi,

I was struggling with an issue whereby an image referenced by relative path ( with or without alias ) in my stylesheet ( I tried both `.scss` and `.css` ) would not be properly output:

I would get  the following in the output css:

```css
.rw-Rune {
  width: 34px;
  height: 34px;
  background: url("data:image/gif;       <---- truncated here
  color: #666;
```

Without any idea where to look, I tried disabling plugins.

Turns out after disabling the `windicss()`  in `plugins` in vite.config.js,  the image is correctly output in resulting css ( but then of course the @apply isn;'t parsed) : 

```css
.rw-Rune {
  @apply flex;
  width: 34px;
  height: 34px;
  background: url("data:image/gif;base64,R0lGODlhHABFAPcAAEJFQCIkIUxOSEhOSkxMRBgZFyAiIC8yKyIjICIiHxocGB0fGlBRSU9RSgAAAEdHQj9CPSosKTc3MiwtKistKx4fHCgpJklKRCcoJAICAgQEA0hKQygpJTY2MR4eG0dJQkZIQiQmIyorJw4PDRobFwoLCBITDzs8N1JUTUJFP2tsYy0uKy    (etc)
  
```

To be sure, I tried main stylesheet both as `.scss` and `.css` . The `.css` file has the same issue, the base64 encoded image referenced in the background property also gets truncated.

Is it possible that the windicss parser somehow doesn't match something properly in those base64 url?

**Comment by voorjaar** [comment]
I just tested it, it seems the problem is not here.

```css
.rw-Rune {
    display: -webkit-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    width: 34px;
    height: 34px;
    background: url("data:image/gif;base64,R0lGODlhHABFAPcAAEJFQCIkIUxOSEhOSkxMRBgZFyAiIC8yKyIjICIiHxocGB0fGlBRSU9RSgAAAEdHQj9CPSosKTc3MiwtKistKx4fHCgpJklKRCcoJAICAgQEA0hKQygpJTY2MR4eG0dJQkZIQiQmIyorJw4PDRobFwoLCBITDzs8N1JUTUJFP2tsYy0uKy");
  }
```

and make sure you are using the latest version of windicss. I will transfer this issue to vite-plugin.
