### ISSUE TITLE
Nesting CSS does not work in scoped Vue style blocks + line comments silently fails instead of throwing errors

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#172]
Example:
```html
<template>
<div class="Comp">
  <div class="Comp-child"></div>
</div>
</template>

<style>
.Comp {
  border: 1px solid red;

  &-child {
    border: 10px solid green;
  }
}
</style>
```

The green border will disappear when changing to `<style scoped>`. 

Turns out that the nesting is incorrect. The resulting CSS should look like this:

``` css
.Comp-childl[data-v-16ba4180] { border: 1px solid green; }
```

But instead WindiCSS compiles it to:

```css
.Comp[data-v-16ba4180]-child[data-v-16ba4180] {
  border: 10px solid green;
}
```

---

Now another related issue, which is not critical but a side effect nonetheless: 

If you add a line comment above `&-child`, like this:

```sass
// A comment
&-child {
  border: 10px solid green;
}
```

All declarations that follow the line comment will just be invalidated, without any compile error. This might trick you into thinking that line comments are supported, but in fact, it just breaks the code silently.
