### ISSUE TITLE
Problem with nesting rule referencing self (&)

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#220]
Here's a nested style that works both with SCSS and postcss-nested plugin:

```html
<div class="Comp is-active">
  <div class="Comp-child"></div>
  <div class="Comp-child"></div>
 </div>
``` 

```scss 
.Comp.is-active {
  &,
  .Comp-child {
    border: 5px solid pink;
  }
}
```

Expected output:

```css
.Comp.is-active, 
.Comp.is-active .Comp-child { 
  border: 5px solid pink; 
}
```

WindiCSS outputs:

```css
.Comp.is-active,
.Comp-child {
  border: 5px solid pink;
}
```
