### ISSUE TITLE
WindiCSS confuses color with font-size if keys are the same

### ISSUE THREAD

**Issue by Mehdi-Hp** [windicss/windicss#246]
Having this configuration,

```js
module.exports = {
    theme: {
        colors: {
             gray: {
                 base: '#59AE90'
             }
       },
       fontSize: {
            base: '125%'
        }
    }
}
```

And later on `<div class="text-gray-base">` results in this:

```css
.text-gray-base {
    font-size: 125%;
}
```

Expected:

```css
.text-gray-base {
    color: #59AE90;
}
```
