### ISSUE TITLE
Feature Request: `initial` as valid custom size 

### ISSUE THREAD

**Issue by UltraCakeBakery** [windicss/windicss#257]
Windicss is amazing. Love it so far!

I just got done replacing 90% of all my tailwindcss classes but there are a couple ones like these that I failed to get rid of yet:
```css
@media (min-width: 768px) {
    .__artwork {
        max-height: initial;
    }
}
```

I tried `max-height-initial` and `max-height-none` but these don't currently generate any styles.
Can this be done in windi? If so, how? If not, consider this a feature request :P
