### ISSUE TITLE
`!important` statements in `@apply` leak out to subsequent style rules

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#262]
Example:

```css
.button {
  @apply text-red-500 !important;
  color: green;
}

/* Output */
.button {
  color: rgba(239, 68, 68, var(--tw-text-opacity)) !important;
  color: green !important;
}
```
