### ISSUE TITLE
Custom colors added by a plugin removed

### ISSUE THREAD

**Issue by sibbng** [windicss/windicss#27]
Hi, I'm switched my Tailwind CSS project to windicss. But unfortunately my custom theming plugin didn't work as expected.

## Reproduction

Repo: https://github.com/sibbng/sibbng.com

```sh
git clone https://github.com/sibbng/sibbng.com.git
cd sibbng.com
yarn
yarn dev
```

## How my custom theming plugin work?

First of all, themes defined in https://github.com/sibbng/sibbng.com/blob/main/theme.yml
My theming plugin is placed on https://github.com/sibbng/sibbng.com/blob/main/themewind.js

This plugin reads yaml file and adds something like these as utility classes:

```css
[data-theme="dark"], [data-theme="light"] {
  --active: #0099FF;
}

[data-theme="dark"] {
  --primary: #111111;
  --on-primary: #B4B4B4;
  --on-primary-active: #F2F2F2;
  --frame: #1E1E1E;
  --on-frame: #808080;
}
[data-theme="light"] {
  --primary: #FFFFFF;
  --on-primary: #888888;
  --on-primary-active: #333333;
  --frame: #EFEFEF;
  --on-frame: #808080;
} 
```

Also extending default theme with these semantic colors:

```js
{
  active: 'var(--active)',
  primary: 'var(--primary)',
  'on-primary': 'var(--on-primary)',
  'on-primary-active': 'var(--on-primary-active)',
  frame: 'var(--frame)',
  'on-frame': 'var(--on-frame)',
  'on-frame-active': 'var(--on-frame-active)'
}
```

In my template I'm using them like `class="bg-primary text-on-primary"`. You can see production deployment of tailwind version at https://sibbng.netlify.app/

That plugin was working in Tailwind. But didn't work in windicss.
