### ISSUE TITLE
How about adding `first-child` and `last-child` variants?

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#272]
A common example would to add quick margin resets to unknown markup content so that the parent container can set the surrounding padding:

```html
<div class="p-5">
  <div class="first-child:mt-0 last-child:mb-0">
    <!-- CMS text content output -->
  </div>
</div>
```

```css
.first-child > *:first-child {
  margin-top: 0;
}
.last-child > *:last-child {
  margin-bottom: 0;
}
```
