### ISSUE TITLE
`loadPlugin` resets variants to defaults

### ISSUE THREAD

**Issue by pedrodim** [windicss/windicss#330]
### What is happening?

Each plugin being loaded overrides the variants with the default variants from `resolveVariants`, thus deleting any variant added by any previous plugin.

https://github.com/windicss/windicss/blob/a1423cf023496b43316271b3cde49f2ea36eb35a/src/lib/index.ts#L972-L973

### What is expected?

Variants from previous plugins should be keep and generated.

### Steps to reproduce

```js
import Processor from 'windicss'

const windi = new Processor({
  plugins: [
    {
      handler: ({ addVariant }) => {
        addVariant('variant', ({ parent }) => parent('.variant'))
      }
    },
    {
      handler: () => {}
    }
  ]
})

console.log(windi.interpret('variant:text-black').styleSheet.build())
```

### Expected output

Variant css is generated.
```css
.variant .variant\:text-black {
  --tw-text-opacity: 1;
  color: rgba(0, 0, 0, var(--tw-text-opacity));
}
```

### Actual output

No output as the variant was deleted by second dumb plugin.
