### ISSUE TITLE
Color callbacks cause errors when using the `theme()` function in CSS

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#337]
I was so darn happy that you had added a way to add custom property color support with [color callback functions](
https://windicss.org/posts/v30-5.html#color-callback-function), but after reconfiguring all my values, I now get errors whenever the color values are used with the `theme()` function:

```css
.no-touch input + div:hover:before {
  border-color: theme('colors.gray.400');
}
```

![image](https://user-images.githubusercontent.com/1736890/121640130-d359a880-ca8d-11eb-99f2-357d82b822d2.png)

In my case, I will just replace these theme values with my custom properties directly, but just wanted to let you know about this side effect.
