### ISSUE TITLE
Is there a way to generate responsive variants of custom classes, ie. @responsive directive

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#351]
Could not find a way to do that in Windi CSS. I though you could do this:

```css
@variants screen {
  .custom {}
}
```
But that didn't work.

**Comment by hannoeru** [comment]
```css
@screen md {
  .custom {}
}
```

**Comment by ahku** [comment]
@hannoeru Will that generate: `.md\:custom {}` for you?

Is there any chance that you will implement `@variants screen` to generate all screen variants for a selector?

**Comment by hannoeru** [comment]
Sorry I didn't get what you mean, that is transform css to apply @media query, maybe plugin is what you're looking for https://windicss.org/plugins/interfaces.html.

**Comment by ahku** [comment]
@hannoeru No worries. I used the wrong directive I think:

From [Tailwind documentation](https://tailwindcss.com/docs/functions-and-directives#responsive):

```css
@responsive {
  .bg-gradient-brand {
    background-image: linear-gradient(blue, green);
  }
}
```

It's a shortcut for `@variants responsive`, and it generates the following:

```css
.bg-gradient-brand {
  background-image: linear-gradient(blue, green);
}

/* ... */

@media (min-width: 640px) {
  .sm\:bg-gradient-brand {
    background-image: linear-gradient(blue, green);
  }
  /* ... */
}

@media  (min-width: 768px) {
  .md\:bg-gradient-brand {
    background-image: linear-gradient(blue, green);
  }
  /* ... */
}

@media (min-width: 1024px) {
  .lg\:bg-gradient-brand {
    background-image: linear-gradient(blue, green);
  }
  /* ... */
}

@media (min-width: 1280px) {
  .xl\:bg-gradient-brand {
    background-image: linear-gradient(blue, green);
  }
  /* ... */
}
```

This would be really useful for generating responsive custom utilities.
