### ISSUE TITLE
How to add custom font

### ISSUE THREAD

**Issue by flakonisto** [windicss/windicss#356]
I didn't find any information about adding custom fonts (from local or via google fonts) to WindiCSS + Gridsome.
Need help with that.

Also I didn't find any official information on this case on the official TailwindCSS documentation.

**Comment by brandiqa** [comment]
Try this for example:

In `index.html`, add your custom font via stylesheet like this:

```html
<head>
<link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
</head>
```

Then in your `App.css`:

```css
html {
  font-family: 'Inter';
}
```

**Comment by Yofou** [comment]
Take a look at https://tailwindcss.com/docs/font-family#customizing

**Comment by brandiqa** [comment]
The question was **adding a custom font**, not **customizing** existing ones. 

Here's a more appropriate link: https://tailwindui.com/documentation#optional-add-the-inter-font-family

However, do note those instructions won't exactly work in WindiCSS as it's supposed to. Use the ones i posted earlier.

**Comment by Yofou** [comment]
> 
> 
> The question was **adding a custom font**, not **customizing** existing ones.
> 
> Here's a more appropriate link: https://tailwindui.com/documentation#optional-add-the-inter-font-family
> 
> However, do note those instructions won't exactly work in WindiCSS as it's supposed to. Use the ones i posted earlier.

I can assure that post above is they offical docs about adding custom fonts hence the header **customizing**, it's what I followed to add them, if you clicked and read you would see the link I sent and you sent are telling the same information

**Comment by brandiqa** [comment]
The documentation you linked is relevant but not complete. It doesn't specify:

1. How to load the custom font
2. How to use a custom font with fallback fonts

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/122887527-93d76a00-d373-11eb-8068-baf9437fd7c5.png)
https://windicss.org/utilities/typography.html#font-family

Note you will need to load the fonts yourself.

**Comment by flakonisto** [comment]
I added Google Font to my index.html in the head.

```
<head>
    <link href="https://fonts.googleapis.com/css2?family=Forum&family=Inter:wght@300;400&display=swap" rel="stylesheet">
</head>
```

And added these fonts to my config.
```
export default defineConfig({
    theme: {
        extend: {
            fontFamily: {
                "sans": 'Inter, sans-serif',
                "serif": 'Forum, serif',
                "body": 'Inter',
            },
        },
    },
})
```

That works fine!

But I want to load custom fonts locally. They don't available on the Google Fonts service.
How can I do it? I mean I place my local fonts for example in the `assets/fonts/`. Will they be available for choosing in my windi config via magic?

**Comment by schelmo** [comment]
you still have to provide the `@font-face` definitions somewhere in your css.
```css
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 300;
  src: url(/assets/fonts/Inter-300.woff2) format('woff2');
}
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  src: url(/assets/fonts/Inter-400.woff2) format('woff2');
}
/* more definitions */
```
then you can use the Inter family in your windi config
