### ISSUE TITLE
[Suggestion] Add child selectors variant

### ISSUE THREAD

**Issue by kingdun3284** [windicss/windicss#358]
Current Behaviour:
```tsx
sibling:after:content-Hi
```
generates
```css
.sibling\:after\:content-Hi::after + * {
  content: "Hi";
}
```
should be:
```css
.sibling\:after\:content-Hi + *::after {
  content: "Hi";
}
```
Idea is to determine the variant order and add corresponding variant after child selector
