### ISSUE TITLE
data uris gets cut by CSSParser

### ISSUE THREAD

**Issue by schelmo** [windicss/windicss#364]
from https://github.com/windicss/vite-plugin-windicss/issues/198
```js
const css = `
.test { 
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAGUlEQVQYV2M4gwH+YwCGIasIUwhT25BVBADtzYNYrHvv4gAAAABJRU5ErkJggg==);
}
`
const processor = new Processor()
const parser = new CSSParser(css, processor)
console.log(parser.parse().build())
```
output:
```css
.test {
  background-image: url(data:image/png;
}
```
( https://jsfiddle.net/aduxb0o5/1/ )
