### ISSUE TITLE
Bug: properties that utilize the `calc()` function do not include spaces causing the property value to be invalid 

### ISSUE THREAD

**Issue by UltraCakeBakery** [windicss/windicss#374]
`class="max-w-[calc(80vw-1rem)]"` generates a invalid property value. There are no spaces around the + - / * operators:
```css
.max-w-\[calc\(80vw-1rem\)\] {
    max-width: calc(80vw-1rem);
}
```

putting a space between around the `-`...

`class="max-w-[80vw - 1rem]"` 

... does not generate any class at all
