### ISSUE TITLE
svg middle

### ISSUE THREAD

**Issue by transtone** [windicss/windicss#398]
```css
svg, img, iframe {
    display: block;
    vertical-align: middle;
}
```
this set will let the `Ant Design Vue v2` icon in the wrong position, like this: 
![image](https://user-images.githubusercontent.com/46688/126592429-d4868490-2d70-4792-b0f1-af5219528bc0.png)

when remove the settings, it goes ok:
![image](https://user-images.githubusercontent.com/46688/126592510-bcc6884e-efb7-4ee6-8944-d6ef13271e1e.png)
