### ISSUE TITLE
Duration and Animate utilities incorrectly generated for JS expressions and HTML tags

### ISSUE THREAD

**Issue by ElMassimo** [windicss/windicss#404]
**Describe the bug**

There seems to be a problem when compiling `animate` and `duration` utilities.

1. Using an `animate` SVG element generates the following CSS

  ```css
  .\<animate {
      -webkit-animation-iteration-count: 1;
      animation-iteration-count: 1
  }
  ```

2. Using a `duration.value` expression in JS generates

  ```css
  .duration\.value {
      -webkit-transition-duration: 150ms;
      -o-transition-duration: 150ms;
      transition-duration: 150ms
  }
  ```

3. Interpolating a variable named `duration` in the template generates

  ```css
  .duration {
      -webkit-transition-duration: 150ms;
      -o-transition-duration: 150ms;
      transition-duration: 150ms
  }
  ```

**Minimal Reproductions**

Created a [repo with a small Vite app](https://github.com/ElMassimo/windicss-tag-repro) that replicates the mentioned bugs.

**Versions**

- vite-plugin-windicss: 1.2.5
- vite: 2.4.3
- framework: vue
