### ISSUE TITLE
After upgrading the plugin from v1.0.0 to v1.0.2, there is a problem with scss in the project

### ISSUE THREAD

**Issue by lainbo** [windicss/windicss#413]
``` javascript
// main.js
import vhCheck from 'vh-check'
vhCheck('browser-address-bar')
```

```css
/* variable.scss */
$full-vh: calc(100vh - var(--browser-address-bar, 0px));
```

``` css
/* global.scss */
.container_height {
  height: calc(#{$full-vh} - 140px);
  overflow-y: auto;
}
```

I tried to use "vh-check" to get a certain correct height of 100vh.
But when I use the class "container_height" in the vue component, in F12 I see that the class "container_height" only has "overflow-y:auto", the height of the calc is missing, I tried v1.0.1 and also have this problem

The only codes in the browser are these
```css
.container_height {
    overflow-y: auto;
}
```
in v1.0.0,The browser has this code
```css
.container_height {
    height: calc(calc(100vh - var(--browser-address-bar, 0px)) - 140px);
    overflow-y: auto;
}
```
