### ISSUE TITLE
How to use cli to parse objects into css files

### ISSUE THREAD

**Issue by awnawnawn** [windicss/windicss#500]
**File Directory**
```
|—— index.html
|—— style.css
|—— windi.config.js
```

**File content**
<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>windicss</title>
</head>
<body>
    <div class="box bg-blue-500 text-red-200"></div>
    <button class="btn m-5 p-5"></button>
</body>
</html>
```

</details>

<details>
<summary>style.css</summary>

```css
.box{
  width: 50px;
  height: 50px;
}
.btn {
  @apply font-bold py-2 px-4 rounded;
}
.btn-blue {
  @apply bg-blue-500 hover:bg-blue-700 text-white;
  padding-top: 1rem;
}
```

</details>

<details>
<summary>windi.config.js</summary>

```js
module.exports = {
  extract: {
      include: [
          "./*.html",
          "./css/*.css"
      ],
      exclude: []
  }
}
```

</details>

**Command**
```shell
$ windicss --config windi.config.js -o ./windi.css
Config file: **\windicss\windi.config.js
Matched files: [ './index.html', './css/style.css' ]
Output file: **\windicss\windi.css
```

**Compiled `windi.css` file**
windi.css
```css
.bg-blue-500 {
  --tw-bg-opacity: 1;
  background-color: rgba(59, 130, 246, var(--tw-bg-opacity));
}
.m-5 {
  margin: 1.25rem;
}
.p-5 {
  padding: 1.25rem;
}
.text-red-200 {
  --tw-text-opacity: 1;
  color: rgba(254, 202, 202, var(--tw-text-opacity));
}
```

The `.btn` and `.box` and others in `style.css` are not resolved yet,
Is it possible to parse the grammar in the css file?
