### ISSUE TITLE
@apply rule creates incorrect output during build, but not during development

### ISSUE THREAD

**Issue by Evertt** [windicss/windicss#522]
I'm using windicss in a SvelteKit project using the Vite plugin and everything is working perfectly, *except* one thing.

In one component I have the following css:

```css
  a {
    @apply border-b-3 pb-1 w-24;
  }

  a.active {
    @apply border-blue-800;
  }
```

Which works fine while I'm working in dev mode, but when I build it for production, I basically get css output like this:

```css
a, a.active {
    --tw-border-opacity: 1;
    border-color: rgba(30, 64, 175, var(--tw-border-opacity));
}
```

So it seems to smush the 2 selectors together and then only apply the utility classes from the last one. I experimented with changing the order, so putting the `a.active { ... }` first and the `a { ... }` second. And when I do that the output is basically:

```css
a.active, a {
    border-bottom-width: 3px;
    padding-bottom: .25rem;
    width: 6rem;
}
```

So it follows the same pattern, it smushes the selectors together and then only applies the utility classes from the last one. Then my next experiment was to check whether it would change anything if I didn't use the `@apply` rule, but just used the raw css rules. So I wrote it like this:

```css
  a {
    border-bottom-width: 3px;
    padding-bottom: 0.25rem;
    width: 6rem;
  }

  a.active {
    --tw-border-opacity: 1;
    border-color: rgba(30, 64, 175, var(--tw-border-opacity));
  }
```

And then the built css turned out okay. That is to say, it was basically identical to what I wrote. So it seems like the `@apply` rule is messing something up. If somebody can try to bugfix this, that would be awesome.

So according to my `package.json` I'm using:
@sveltejs/kit next
Svelte ^3.43.0
vite-plugin-windicss ^1.4.12
windicss ^3.1.9

Hope that that's enough information to bugfix this.

### edit

Just some more information I gathered after some more experimentation. Everything also works fine if I just use the `@apply` rule in one of the selectors, instead of both. Then it also produces the correct css during the build process.
