### ISSUE TITLE
Support changing important modifier - convert `!` to `i-`

### ISSUE THREAD

**Issue by transtone** [windicss/windicss#528]
**Is your feature request related to a problem? Please describe.**
I use windicss in wechat miniapp with https://github.com/pcdotfan/taro-plugin-tailwind, 
but wechat miniapp's wxss can't support slash and backslash as a classname, some widicss feature can't use.

**Describe the solution you'd like**
Is there a plan to translate `!text-green-300` to `i-text-green-300`, to avoid a backslash in classname?
before:
```css
.\!text-green-300 {
  --tw-text-opacity: 1 !important;
  color: rgba(110, 231, 183, var(--tw-text-opacity)) !important;
}
```
after:
```css
.i-text-green-300 {
  --tw-text-opacity: 1 !important;
  color: rgba(110, 231, 183, var(--tw-text-opacity)) !important;
}
```
