### ISSUE TITLE
regression in attributify

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss#542]
we do have some regression in attributify mode with latest release 3.2.0.
See full comparison below. But `'dark:dark-blue-600',` is not interpreted into  
```css
.dark [border~="dark:dark-blue-600"] {
  --tw-border-opacity: 1;
  border-*-color: rgba(37, 99, 235, var(--tw-border-opacity));
}
```
instead it is somehow generating broken rule
```css
[border~=""] {
  border-width: 1px;
}
```

---
### Full Comparison
`< 3.2.0`
```js
/* input */
{
  border: [
    '~',
    'rounded-sm',
    'blue-300',
    'gray-300',
    'dark:dark-blue-600',
    'group-hover:blue-300',
    '\n',
    'hover:blue-300',
    ''
  ]
}
```

```css
/* output */
[border~="blue-300"] {
  --tw-border-opacity: 1;
  border-color: rgba(147, 197, 253, var(--tw-border-opacity));
}
[border~="gray-300"] {
  --tw-border-opacity: 1;
  border-color: rgba(209, 213, 219, var(--tw-border-opacity));
}
.group:hover [border~="group-hover:blue-300"] {
  --tw-border-opacity: 1;
  border-color: rgba(147, 197, 253, var(--tw-border-opacity));
}
[border~="hover:blue-300"]:hover {
  --tw-border-opacity: 1;
  border-color: rgba(147, 197, 253, var(--tw-border-opacity));
}
.dark [border~="dark:dark-blue-600"] {
  --tw-border-opacity: 1;
  border-*-color: rgba(37, 99, 235, var(--tw-border-opacity));
}
[border~="rounded-sm"] {
  border-radius: 0.125rem;
}
[border~="~"] {
  border-width: 1px;
}
```

---

`>= 3.2.0`
```js
/* input */
{
  border: [
    '~',
    'rounded-sm',
    'blue-300',
    'gray-300',
    'dark:dark-blue-600',
    'group-hover:blue-300',
    '\n',
    'hover:blue-300',
    ''
  ]
}
```
```css
/* output */
[border~="blue-300"] {
  --tw-border-opacity: 1;
  border-color: rgba(147, 197, 253, var(--tw-border-opacity));
}
[border~="gray-300"] {
  --tw-border-opacity: 1;
  border-color: rgba(209, 213, 219, var(--tw-border-opacity));
}
.group:hover [border~="group-hover:blue-300"] {
  --tw-border-opacity: 1;
  border-color: rgba(147, 197, 253, var(--tw-border-opacity));
}
[border~="hover:blue-300"]:hover {
  --tw-border-opacity: 1;
  border-color: rgba(147, 197, 253, var(--tw-border-opacity));
}
[border~="rounded-sm"] {
  border-radius: 0.125rem;
}
[border~="~"] {
  border-width: 1px;
}
[border~=""] {
  border-width: 1px;
}
```
