### ISSUE TITLE
How to define the default unit?

### ISSUE THREAD

**Issue by okxiaoliang4** [windicss/windicss#610]
like define default unit 'px'

html input:
```html
<div class="w-10"></div>
```

css output:
```css
.w-10 {
  width: 10px;
}
```

**Comment by lizy0329** [comment]
w-[10px]

**Comment by okxiaoliang4** [comment]
I want to omit the `px`

**Comment by Techassi** [comment]
Windi uses the default spacing like:

```css
.w-1 {
  width: 0.25rem;
}

.w-4 {
  width: 1rem;
}
```

If you want to customize it, you can use:

```js
export default {
  theme: {
    spacing: {
      1: '1px',
      10: '10px',
    },
  },
}
```

This has one huge drawback: You need to define all your sizes manually. @lizy0329 suggestion is the recommended way to achieve this behavior.
