### ISSUE TITLE
preflight function does not produce the expected output

### ISSUE THREAD

**Issue by danieldietrich** [windicss/windicss#647]
I tested this on a macOS with Safari.

## Initial style sheet

First, I build an initial preflight StyleSheet

```js
const initialStyleSheet = processor.preflight("<H1 <SCRIPT", 
        true,  // includeBase
        true,  // includeGlobal
        true,  // includePlugins
        false  // ignoreProcessed
)
```

It looks like `h1` is missing:

```css
*, ::before, ::after {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  border-width: 0;
  border-style: solid;
  border-color: #e5e7eb;
}
* {
  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
}
:root {
  -moz-tab-size: 4;
  -o-tab-size: 4;
  tab-size: 4;
}
:-moz-focusring {
  outline: 1px dotted ButtonText;
}
:-moz-ui-invalid {
  box-shadow: none;
}
::moz-focus-inner {
  border-style: none;
  padding: 0;
}
::-webkit-inner-spin-button, ::-webkit-outer-spin-button {
  height: auto;
}
::-webkit-search-decoration {
  -webkit-appearance: none;
}
::-webkit-file-upload-button {
  -webkit-appearance: button;
  font: inherit;
}
[type='search'] {
  -webkit-appearance: textfield;
  outline-offset: -2px;
}
abbr[title] {
  -webkit-text-decoration: underline dotted;
  text-decoration: underline dotted;
}
body {
  margin: 0;
  font-family: inherit;
  line-height: inherit;
}
html {
  -webkit-text-size-adjust: 100%;
  font-family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
  line-height: 1.5;
}
```

## Extending style sheet

When adding elements to the html page, there might happen subsequent preflight calls. I extend the initial style sheet described above like this:

```js
initialStyleSheet.extend(
    processor.preflight("<DIV <P <BUTTON", 
        false, // includeBase
        false, // includeGlobal
        false, // includePlugins
        true   // ignoreProcessed
    )
)
```

However, `processor.preflight("<DIV <P <BUTTON", false, false, false, true)` returns an empty StyleSheet. I think this is a bug.

Side-question: am I doing it right to pass `...[true, true, true, false]` to the first `preflight()` call and `[false, false, false, true]` to subsequent `preflight()` calls that only process new tag names?
