### ISSUE TITLE
duplicates in devtools with attributify mode

### ISSUE THREAD

**Issue by woldtwerk** [windicss/windicss#656]
Hi there,
I always get a lot of duplicates in devtools during dev mode. As far as I can tell this only happens with attributify mode. In prod build there are no duplicates.

![image](https://user-images.githubusercontent.com/32794633/149174840-5f41fff1-7d27-4c71-b28a-2f6fbe322690.png)

config:
```js
import { defineConfig } from 'windicss/helpers'
import typography from 'windicss/plugin/typography'

export default defineConfig({
  darkMode: 'class',
  // https://windicss.org/posts/v30.html#attributify-mode
  attributify: true,
  extract: {
    include: ['src/**/*.{vue,html,jsx,tsx,ts,astro}'],
    exclude: ['node_modules', '.git', 'dist'],
  },
  plugins: [
    typography(),
  ],
})
```

I love attributify mode, but this drives me crazy. Any suggestions?
thx =)

**Comment by Hrishikesh-K** [comment]
I' seeing this happen in my Vite+Vue project too. However, I can ignore it during dev mode as that's probably being caused by HMR (just my guess).

However, the more concerning part is that, I'm seeing this happen even in production. I've a Hugo project and I'm using Windi CLI.

My command is:

```
windicss --attributify --config ./windi.config.js --minify --output ./assets/css/windi.css --preflight --style
```

and config is:

```js
const {defineConfig} = require('windicss/helpers')
module.exports = defineConfig({
  attributify: {
    prefix: 'w-'
  },
  extract: {
    include: [
      './content/**/*.md',
      './layouts/**/*.html'
    ]
  }
})
```

My generated CSS looks like:

```css
[w-bg~="white"] {
  --tw-bg-opacity: 1;
  background-color: rgba(255, 255, 255, var(--tw-bg-opacity))
}

[w-display="block"] {
  display: block
}

[w-display~="block"] {
  display: block
}

[w-flex="~"] {
  display: -webkit-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex
}

[w-flex~="~"] {
  display: -webkit-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex
}

[w-grid~="~"] {
  display: -ms-grid;
  display: grid
}

[w-flex~="col"] {
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -ms-flex-direction: column;
  -webkit-flex-direction: column;
  flex-direction: column
}
```

That's just an example, but there are more instances of duplicates.
