### ISSUE TITLE
"@apply" compile error in SFC Less

### ISSUE THREAD

**Issue by keuby** [windicss/windicss#667]
In SFC less style block, when values such as `p-1.5` and `w-12.5` are used, the 0.5 is ignored, for example

```less
.custom-class {
    @apply pt-1.5;
}
```

Theoretically it should be compiled to

```css
.custom-class {
    padding-top: 0.375rem;
}
```

It's actually compiled to

```css
.custom-class {
    padding-top: 0.25rem;
}
```

and this is the value of pt-1
