### ISSUE TITLE
bug: `::selection` rules do not apply to children (as opposed to tailwind)

### ISSUE THREAD

**Issue by wtho** [windicss/windicss#681]
When adding e. g. `selection:text-white`, in tailwind these rules are applied, so all children also apply the styles:
```css
.selection\:text-white::selection {
    --tw-text-opacity: 1;
    color: rgb(255 255 255 / var(--tw-text-opacity));
}
.selection\:text-white *::selection {
    --tw-text-opacity: 1;
    color: rgb(255 255 255 / var(--tw-text-opacity));
}
```
created [here in Tailwind](https://github.com/tailwindlabs/tailwindcss/blob/bab689ca8284265f51d5b66a1f3f1007850d97c1/src/corePlugins.js#L23)

In windicss, I see only this rule:
```css
.selection\:text-white::selection {
    --tw-text-opacity: 1;
    color: rgba(255, 255, 255, var(--tw-text-opacity));
}
```
created [here in windi](https://github.com/windicss/windicss/blob/ff6f69897b46faac269344173abd93b43f36892e/src/lib/variants/state.ts#L64)

Probably this should be:
```diff
    file: () => new Style().pseudoElement('file-selector-button'),
-   selection: () => new Style().pseudoElement('selection'),
+   selection: () => new Style().wrapSelector(selector => `${selector} *::selection, ${selector}::selection`),
    marker: () => new Style().wrapSelector(selector => `${selector} *::marker, ${selector}::marker`),
```
