### ISSUE TITLE
Litepie support

### ISSUE THREAD

**Issue by acidjazz** [windicss/windicss#760]
I was trying to implement [litepie](https://litepie.com/) - I noticed it generated a class with a 500px ring-shadow

```css
.focus\:ring-litepie-primary-500:focus {
    --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
    --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(500px + var(--tw-ring-offset-width)) var(--tw-ring-color);
    box-shadow: var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow,0 0 #0000);
}
```

I was able to override this class but thought I'd report it
