### ISSUE TITLE
Custom fonts literally doesn't work??

### ISSUE THREAD

**Issue by hrqmonteiro** [windicss/windicss#783]
I have the font imported from Google fonts in my Next.js `_document.tsx` file:

```
import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <link
            href='https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap'
            rel='stylesheet'
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
```

Have this in my `globals.css` file:

```
html,
body {
  @apply font-sans;
  padding: 0;
  margin: 0;
  font-family: 'Raleway';
}

a {
  color: inherit;
  text-decoration: none;
}

* {
  box-sizing: border-box;
}
```

And on my `windi.config.ts`:

```
import { defineConfig } from 'windicss/helpers'
import defaultTheme from 'windicss/defaultTheme'

export default defineConfig({
  extract: {
    include: ['**/*.{jsx,tsx,css}'],
    exclude: ['node_modules', '.git', '.next']
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Raleway"', ...defaultTheme.fontFamily.sans].join(',')
      }
    }
  }
})
```

And it doesn't work.

**Comment by hrqmonteiro** [comment]
![Screenshot from 2022-05-23 19-21-17](https://user-images.githubusercontent.com/17055027/169914299-0966152e-e2de-4f0d-bbbc-78cde00bfe85.png)

**Comment by qucode1** [comment]
I've got the same issue. Custom font families do not work.

Package Versions:
```
...
nuxt-windicss 2.3.1
nuxt3 3.0.0-rc.3-27550969.a4a3cff
typescript 4.6.4
vite 2.9.9
vue 3.2.36
webpack 5.72.1
windicss 3.5.4
...
```

`nuxt.config.ts`
```js
  css: [
    '@/assets/fonts.css'
  ],
```

`fonts.css`
```css
  @font-face {
    font-family: 'Roboto Bold';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('../assets/fonts/roboto-bold-webfont.ttf') format('truetype'),
    url('../assets/fonts/roboto-bold-webfont.woff') format('truetype'),
    url('../assets/fonts/roboto-bold-webfont.woff2') format('truetype');
  }
  
  @font-face {
    font-family: 'Roboto Regular';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('../assets/fonts/roboto-regular-webfont.ttf') format('truetype'),
    url('../assets/fonts/roboto-regular-webfont.woff') format('truetype'),
    url('../assets/fonts/roboto-regular-webfont.woff2') format('truetype');
  }
  
  @font-face {
    font-family: 'Roboto Medium';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('../assets/fonts/roboto-medium-webfont.ttf') format('truetype'),
    url('../assets/fonts/roboto-medium-webfont.woff') format('truetype'),
    url('../assets/fonts/roboto-medium-webfont.woff2') format('truetype');
  }
  
  @font-face {
    font-family: 'Roboto Light';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('../assets/fonts/roboto-light-webfont.ttf') format('truetype'),
    url('../assets/fonts/roboto-light-webfont.woff') format('truetype'),
    url('../assets/fonts/roboto-light-webfont.woff2') format('truetype');
  }
```

`windi.config.ts`
```js
  theme: {
    extend: {
      fontFamily: {
        'roboto-regular': ['Roboto Regular', 'sans-serif'],
        'roboto-light': ['Roboto Light', 'sans-serif'],
        'roboto-bold': ['Roboto Bold', 'sans-serif'],
      }
    }
  },
```
`someFile.vue`
```vue
  <a class="text-[18px] mb-0.5 block font-roboto-bold" :href="subNode.url">
    {{ subNode.linkText }}
  </a>
```

The font-family does not show up in the class, only the font-weight. Using `font-roboto-regular` does not have any styles at all.

![Bildschirmfoto 2022-05-27 um 15 33 32](https://user-images.githubusercontent.com/28145834/170709789-04ea2dc3-d4b2-40cd-ba73-719f0e0235cf.png)
