### ISSUE TITLE
"class=" doesn't be scanned on Attributify mode via Windi CSS CLI

### ISSUE THREAD

**Issue by Lastor-Chen** [windicss/windicss#785]
I use Windi CSS CLI to compile css file on PHP twig template, it works fine on dev mode. But it doesn't working when dev mode is removed.

Example code
```twig
{# test.twig #}
<h1 class="mb-1" md="mb-2">Hello</h1>
```

CLI command on production mode (ignore --minify)
```bash
$ windicss ./test.twig -ao ./test.css
```

Output CSS
```css
/* class="mb-1" is missing */
@media (min-width: 768px) {
  [md="mb-2"] {
    margin-bottom: 0.5rem;
  }
}
```

CLI command with dev mode
```bash
$ windicss ./test.twig -ao ./test.css --dev
```

Output CSS
```css
/* class="mb-1" is scanned only on dev mode */
.mb-1 {
  margin-bottom: 0.25rem;
}
@media (min-width: 768px) {
  [md="mb-2"] {
    margin-bottom: 0.5rem;
  }
}
```

Have I done something wrong? Or is this expected behavior?
I used windicss v3.5.4
