### ISSUE TITLE
CSS Variables + Gradient + Attributify

### ISSUE THREAD

**Issue by Hrishikesh-K** [windicss/windicss#791]
Hi,

I'm trying to use gradients like:

```html
<html>
  <head>
    <style
      lang = "windi">
      :root {
        --blue500: #040e4e;
        --red500: #470b1b;
      }
    </style>
  </head>
  <body>
    <div
      w-gradient = "from-blue500 to-red500"
      w-h = "40"
      w-w = "40">
    </div>
  </body>
</html>
```

I have my colours in `windi.config.js` defined like:

```js
import {defineConfig} from 'windicss/helpers'
export default defineConfig({
  theme: {
    colors: {
      blue500: 'var(--blue500)',
      red500: 'var(--red500)',
    }
  }
})
```

This fails, because the generated styles include:

```css
[w-gradient~="to-red500"] {
  --tw-gradient-to: rgba(var(--red500), var(--tw-to-opacity, 1));
}
[w-gradient~="from-blue500"] {
  --tw-gradient-from: rgba(var(--blue500), var(--tw-from-opacity, 1));
  --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(255, 255, 255, 0));
}
```

The problem is, my CSS variables are defined in HEX value, but Windi is treating it as RGBA. This results in no gradient being applied to the `<div>`.
