### ISSUE TITLE
custom fontSizes as String and lineHeight as second array item misbehave

### ISSUE THREAD

**Issue by schelmo** [windicss/windicss#80]
config:
```js
module.exports = {
  theme: {
    fontSize: {
      main: '1.25rem',
    }
  }
}
```

the resulting class ist:
```css
.text-main {
  font-size: 1;
}
```

its working if changing it to array:
main: ['1.25rem'],

also the lineHeight is not attached if you specify it as second array item:
main: ['1.25rem', '2rem']
```css
.text-main {
    font-size: 1.25rem;
}
```
while using an object works:
main: ['1.25rem', {lineHeight: '2rem'}]
