### ISSUE TITLE
[Feature] `prefixedOnly` for attributify

### ISSUE THREAD

**Issue by Hrishikesh-K** [windicss/windicss#825]
Hi!

I recently discovered this option in UnoCSS: https://github.com/unocss/unocss/tree/main/packages/preset-attributify/#properties-conflicts, and was wondering if it's possible to port this option to WindiCSS too.

The reason being, I've some attributes like:

```html
<div
  w-border = "rounded-md">
</div>
```

I can see that, in the generated CSS file, I get:

```css
.rounded-md {
  border-radius: .375rem
}
[w-border~=rounded-md] {
  border-radius: .375rem
}
```

This is just one example, but there are a few more utilities having this problem.

I believe that's happening because `rounded-md` can also be used as a class name. This can possibly be avoided by providing the above option.
