### ISSUE TITLE
Issue with gridTemplateColumns generation

### ISSUE THREAD

**Issue by nicooprat** [windicss/windicss#83]
Here's my tailwind.config.js file:

```js
const { gridTemplateColumns } = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    gridTemplateColumns: {
      ...gridTemplateColumns,
      list: 'repeat(auto-fit, minmax(16em, 1fr))',
    },
  },
}
```

Here's what was generated with Tailwind:

```css
.grid-cols-list {
  grid-template-columns: repeat(auto-fit, minmax(16em, 1fr));
}
```

Here's what is generated with Windi:

```css
.grid-cols-list {
  grid-template-columns: repeat(repeat(auto-fit, minmax(16em, 1fr)), minmax(0, 1fr));
}
```

Tailwind docs: https://tailwindcss.com/docs/grid-template-columns
Windi code: https://github.com/windicss/windicss/blob/5fcae337dc27dc411c244bb8f0037283615edb21/src/lib/utilities/dynamic.ts#171

It seems this code only handles default config (from 1 to 12) but doesn't allow entirely custom values. Is it on purpose? Did I miss something?

Thanks!

**Comment by nicooprat** [comment]
Thanks for your quick fix. Couldn't test it for now, but I found out that the default rules don't work neither:

```css
.grid-cols-4 {
    grid-template-columns: repeat(repeat(4, minmax(0, 1fr)), minmax(0, 1fr));
}
```

Hope it fixes this too.

Also, the same bugs should be present in `grid-template-rows` too I guess: https://tailwindcss.com/docs/grid-template-rows
