### ISSUE TITLE
怎样避免在构建后的css中使用css variable？

### ISSUE THREAD

**Issue by 269378737** [windicss/windicss#846]
比如`windicss`默认生成的带`css variable`的样式是这样：
```css
.bg-black {
  --tw-bg-opacity: 1;
  background-color: rgba(0, 0, 0, var(--tw-bg-opacity));
}
.border-black {
  --tw-border-opacity: 1;
  border-color: rgba(0, 0, 0, var(--tw-border-opacity));
}
```
但是我想生成没有`css variable`的，像这样：
```css
.bg-black {
  background-color: rgba(0, 0, 0, 1);
}
.border-black {
  border-color: rgba(0, 0, 0, 1);
}
```

请问要解决这个问题该怎么做呢？
