### ISSUE TITLE
How to support all property?

### ISSUE THREAD

**Issue by peterroe** [windicss/windicss#847]
Like this:
```css
.all-revert {
  all: revert
}
```
